id: I5F9BBBB8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T00:21:28+00:00'
last_modified: '2022-06-07T12:44:33.984793+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG489
  title: བོད་བརྒྱུད་ནང་བསྟན་ལྷ་སྐུའི་བཟོ་རྩལ་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    34CD:
      image_group_id: I1KG497
      title: ''
      total_pages: 374
      order: 1
      base_file: 34CD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
